### ISSUE TITLE
Tests on DB timed out

### ISSUE THREAD

**Issue by FiliTol** [MutinyWallet/harbor#69]
I come to this issue after having resolved #68. That issue may contain useful details.
I've built the app using rust in debian 12.

### Expected behaviour

 `cargo test --features vendored` results into 6 succesful tests. Opening the app and inserting the password the first time saves the password and then every time the password is provided the app is unlocked (and thus the DB I guess).

### Actual behaviour

`cargo test --features vendored` returns all failed tests with the following errors:

```
[master][~/repositories/harbor]$ cargo test --features vendored
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.61s
     Running unittests src/main.rs (target/debug/deps/harbor-775601e9a9433194)

running 6 tests
test db::tests::test_lightning_receive_db ... FAILED
test db::tests::test_onchain_payment_db ... FAILED
test db::tests::test_onchain_receive_db ... FAILED
test db::tests::test_seed ... FAILED
test db::tests::test_lightning_payment_db ... FAILED
test db::tests::test_insert_new_federation ... FAILED

failures:

---- db::tests::test_lightning_receive_db stdout ----
thread 'db::tests::test_lightning_receive_db' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection

---- db::tests::test_onchain_payment_db stdout ----
thread 'db::tests::test_onchain_payment_db' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection

---- db::tests::test_onchain_receive_db stdout ----
thread 'db::tests::test_onchain_receive_db' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- db::tests::test_seed stdout ----
thread 'db::tests::test_seed' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection

---- db::tests::test_lightning_payment_db stdout ----
thread 'db::tests::test_lightning_payment_db' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection

---- db::tests::test_insert_new_federation stdout ----
thread 'db::tests::test_insert_new_federation' panicked at src/db.rs:425:54:
Could not setup db: timed out waiting for connection


failures:
    db::tests::test_insert_new_federation
    db::tests::test_lightning_payment_db
    db::tests::test_lightning_receive_db
    db::tests::test_onchain_payment_db
    db::tests::test_onchain_receive_db
    db::tests::test_seed

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.01s

error: test failed, to rerun pass `--bin harbor
```

If trying to start the app the first time, every attempt to insert the password return "Error: timed out waiting for connection".
The logs in the CLI show `ERROR harbor::core > error using password: timed out waiting for connection`

The following is the content of the folder "migrations/"

```
.
└── 2024-05-13-234832_create_config
    ├── down.sql
    └── up.sql
```

If trying to execute a basic query of those sqlite files, the result is the following:

```
[master][~/repositories/harbor/migrations/2024-05-13-234832_create_config]$ sqlite3
SQLite version 3.46.0 2024-05-23 13:25:27
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open down.sql
sqlite> SELECT name
   ...> FROM sqlite_master
   ...> WHERE type='table';
Parse error: file is not a database (26)
```

**Comment by TonyGiorgio** [comment]
The tests fail, but does the application run normally for you?

Maybe changing this line to 30 would help? 

https://github.com/MutinyWallet/harbor/blob/45d7e2520554b1035b0074f4f343033fb55b4e45/src/db.rs#L28

**Comment by FiliTol** [comment]
Changed the variable value to 30 sec as you suggested, then the app does work!

I managed to startup the app and I added a mint code from bitcoinmints.com.
Then, when closing the app and running again `cargo run --features vendored`, the login get stucked and the following backtrace is returned:

```
[master][~/repositories/harbor]$ RUST_BACKTRACE=1 cargo run --features vendored
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/harbor`
Core loaded
thread 'tokio-runtime-worker' panicked at src/core.rs:432:30:
Could not create fedimint client: io error: unexpected end of file

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.83/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/result.rs:1964:27
   2: harbor::fedimint_client::FedimintStorage::new::{{closure}}
             at ./src/fedimint_client.rs:617:28
   3: harbor::fedimint_client::FedimintClient::new::{{closure}}
             at ./src/fedimint_client.rs:76:75
   4: harbor::core::run_core::{{closure}}::{{closure}}
             at ./src/core.rs:431:30
   5: <futures_util::stream::once::Once<Fut> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/once.rs:46:33
   6: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26
   7: futures_util::stream::select_with_strategy::poll_side
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:220:28
   8: futures_util::stream::select_with_strategy::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:243:11
   9: <futures_util::stream::select_with_strategy::SelectWithStrategy<St1,St2,Clos,State> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:270:17
  10: <futures_util::stream::select::Select<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select.rs:115:9
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  13: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  14: futures_util::future::future::FutureExt::poll_unpin
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:118:35
  16: iced_futures::subscription::tracker::Tracker::update::{{closure}}
             at /home/user/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/b30d34f/futures/src/subscription/tracker.rs:102:34
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/future/future.rs:123:9
  18: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  19: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  21: tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  22: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panic/unwind_safe.rs:272:9
  24: std::panicking::try::do_call
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:559:40
  25: __rust_try
  26: std::panicking::try
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:523:19
  27: std::panic::catch_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panic.rs:149:14
  28: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  30: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  31: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  32: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  33: tokio::runtime::task::LocalNotified<S>::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:427:9
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  35: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  36: tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  37: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  38: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  39: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  40: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  41: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/local.rs:286:12
  43: std::thread::local::LocalKey<T>::with
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/local.rs:262:9
  44: tokio::runtime::context::set_scheduler
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  45: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  46: tokio::runtime::context::runtime::enter_runtime
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  47: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  48: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  49: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42:21
  50: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  51: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  52: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  53: tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  54: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  55: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panic/unwind_safe.rs:272:9
  56: std::panicking::try::do_call
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:559:40
  57: __rust_try
  58: std::panicking::try
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:523:19
  59: std::panic::catch_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panic.rs:149:14
  60: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  61: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  62: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  63: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  64: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  65: tokio::runtime::task::UnownedTask<S>::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:464:9
  66: tokio::runtime::blocking::pool::Task::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:159:9
  67: tokio::runtime::blocking::pool::Inner::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:513:17
  68: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:471:13
  69: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/sys_common/backtrace.rs:155:18
  70: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/mod.rs:542:17
  71: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panic/unwind_safe.rs:272:9
  72: std::panicking::try::do_call
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:559:40
  73: __rust_try
  74: std::panicking::try
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:523:19
  75: std::panic::catch_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panic.rs:149:14
  76: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/mod.rs:541:30
  77: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/ops/function.rs:250:5
  78: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/alloc/src/boxed.rs:2022:9
  79: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/alloc/src/boxed.rs:2022:9
  80: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/sys/pal/unix/thread.rs:108:17
  81: start_thread
             at ./nptl/pthread_create.c:442:8
  82: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/result.rs:1034:23
   4: harbor::core::run_core::{{closure}}::{{closure}}
             at ./src/core.rs:422:42
   5: <futures_util::stream::once::Once<Fut> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/once.rs:46:33
   6: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26
   7: futures_util::stream::select_with_strategy::poll_side
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:220:28
   8: futures_util::stream::select_with_strategy::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:243:11
   9: <futures_util::stream::select_with_strategy::SelectWithStrategy<St1,St2,Clos,State> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select_with_strategy.rs:270:17
  10: <futures_util::stream::select::Select<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/select.rs:115:9
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  13: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  14: futures_util::future::future::FutureExt::poll_unpin
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:118:35
  16: iced_futures::subscription::tracker::Tracker::update::{{closure}}
             at /home/user/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/b30d34f/futures/src/subscription/tracker.rs:102:34
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/future/future.rs:123:9
  18: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  19: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  21: tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  22: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panic/unwind_safe.rs:272:9
  24: std::panicking::try::do_call
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:559:40
  25: __rust_try
  26: std::panicking::try
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:523:19
  27: std::panic::catch_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panic.rs:149:14
  28: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  30: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  31: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  32: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  33: tokio::runtime::task::LocalNotified<S>::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:427:9
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  35: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  36: tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  37: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  38: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  39: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  40: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  41: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/local.rs:286:12
  43: std::thread::local::LocalKey<T>::with
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/thread/local.rs:262:9
  44: tokio::runtime::context::set_scheduler
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  45: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  46: tokio::runtime::context::runtime::enter_runtime
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  47: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  48: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  49: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42:21
  50: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  51: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  52: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  53: tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  54: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  55: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/core/src/panic/unwind_safe.rs:272:9
  56: std::panicking::try::do_call
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:559:40
  57: __rust_try
  58: std::panicking::try
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panicking.rs:523:19
  59: std::panic::catch_unwind
             at /rustc/ef0027897d2e9014766fb47dce9ddbb925d2f540/library/std/src/panic.rs:149:14
  60: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  61: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  62: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  63: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  64: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  65: tokio::runtime::task::UnownedTask<S>::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:464:9
  66: tokio::runtime::blocking::pool::Task::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:159:9
  67: tokio::runtime::blocking::pool::Inner::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:513:17
  68: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by FiliTol** [comment]
Okay, that was the issue. I deleted the .harbor folder and rebuilt the project.
Now everything works properly with the signet mint.

Thanks

**Comment by TonyGiorgio** [comment]
Great, thank you for testing this and getting it working!
